### PR TITLE
Take into account TZ env in container

### PR DESCRIPTION
**Pull request by dmartinpro**

### CODE REVIEW

**Comment by Domochip** [comment]
What's the effect of adding this lib?

**Comment by Domochip** [comment]
up

**Comment by Domochip** [comment]
up

**Comment by dmartinpro** [comment]
It contains Timezone information to let you define TZ env variable.
see: https://www.iana.org/time-zones

**Comment by Domochip** [comment]
Why adding TZ? What is the use case?

**Pull request closed without merging**
